words = [
  "afl",
  "asan",
  "autodict",
  "backdrop",
  "bsp",
  "cbor",
  "ciborium",
  "classpath",
  "coursier",
  "dotty",
  "ffm",
  "jdk",
  "jsonrpc",
  "jvm",
  "lsp",
  "lsp4j",
  "mmap",
  "openjdk",
  "quiescence",
  "scala",
  "scalameta",
  "semanticdb",
  "serde",
  "shmem",
  "sigsegv",
  "sqlite",
  "stdio",
  "zaozi",
]
